### ISSUE TITLE
bug in evaluateValidation

### ISSUE THREAD

**Issue by vshioshvili** [jason-p-pickering/datim-validation#81] opened 2020-04-28 15:39 UTC
There is an issue with these two lines:
https://github.com/jason-p-pickering/datim-validation/blob/5a3f9f04265ba1ecaf6236a09abc04b4b4875994/R/evaluateValidation.R#L79

https://github.com/jason-p-pickering/datim-validation/blob/5a3f9f04265ba1ecaf6236a09abc04b4b4875994/R/evaluateValidation.R#L81

The problem is that the expression pattern is for `#{UID}` (when no COC is present) style value, while expression itself is `UID`, resulting in no substitution, which causes error farther down on lines:
https://github.com/jason-p-pickering/datim-validation/blob/5a3f9f04265ba1ecaf6236a09abc04b4b4875994/R/evaluateValidation.R#L138
and
https://github.com/jason-p-pickering/datim-validation/blob/5a3f9f04265ba1ecaf6236a09abc04b4b4875994/R/evaluateValidation.R#L142

if data file only has values for one side of the validation, causing an error like:

```
> df_validate <- validateData(data = d, datasets = ds_current,return_violations_only = TRUE)

Error in eval(parse(text = x)) : object 'N6fw6CjSHSc' not found

Error: with piece 1: 

    dataElement period    orgUnit categoryOptionCombo attributeOptionCombo value                      combi
... [rest of the error content trimmed]
```

I suppose it is because:
`expression.pattern<-"[a-zA-Z][a-zA-Z0-9]{10}(\\.[a-zA-Z][a-zA-Z0-9]{10})?"`
was changed in the last modification to:
`expression.pattern<-"#\\{[a-zA-Z][a-zA-Z0-9]{10}(\\.[a-zA-Z][a-zA-Z0-9]{10})?\\}"`

**Comment by vshioshvili** [comment] 2020-04-28 18:08
Also, not sure if it is related, but the current codebase erroneously flags a record as violating exclusive pair (`:OR:`) rule, even when there is a single record in the file being validated.

**Comment by jason-p-pickering** [comment] 2020-04-29 07:18
Thanks for the detailed debugging. I'll try and see if I can get this fixed quickly.

**Comment by jason-p-pickering** [comment] 2020-04-29 10:53
I was not able to replicate this issue, but I think this is what happened. 

1) A copy of the validation rules from `getValidationRules` was present in the cache from an older version of the code. 
2) In the meantime, the code was updated to use the new version of master. 
3) The old cached object was retrieved, but not valid with the new code. 

After clearing the cache, I think this should work. 

Was not able to reproduce on two different environments, but this could be a problem with the cache logic, namely that objects which are older than 7 days are not being properly refreshed. 

Going to close this for now, but if the problem persists, please re-open @vshioshvili

**Closed by jason-p-pickering** 2020-04-29 10:53 UTC
